[08/Nov/2018 05:51:46] "GET /index HTTP/1.0" 301 0
Internal Server Error: /index/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/utils.py", line 66, in __getitem__
    return self._engines[alias]
KeyError: 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/website/mysite/blog/views.py", line 53, in home
    'posts':posts})
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/loader.py", line 12, in get_template
    engines = _engine_list(using)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/loader.py", line 66, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/utils.py", line 90, in all
    return [self[alias] for alias in self]
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/utils.py", line 90, in <listcomp>
    return [self[alias] for alias in self]
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/utils.py", line 81, in __getitem__
    engine = engine_cls(params)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 25, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 43, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 108, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 121, in get_package_libraries
    module = import_module(entry[1])
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/website/mysite/blog/templatetags/blog_tags.py", line 19, in <module>
    @register.assignment_tag
AttributeError: 'Library' object has no attribute 'assignment_tag'
[08/Nov/2018 05:51:46] "GET /index/ HTTP/1.0" 500 149194
Not Found: /favicon.ico
[08/Nov/2018 05:51:48] "GET /favicon.ico HTTP/1.0" 404 2476
Internal Server Error: /index/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/utils.py", line 66, in __getitem__
    return self._engines[alias]
KeyError: 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/website/mysite/blog/views.py", line 53, in home
    'posts':posts})
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/loader.py", line 12, in get_template
    engines = _engine_list(using)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/loader.py", line 66, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/utils.py", line 90, in all
    return [self[alias] for alias in self]
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/utils.py", line 90, in <listcomp>
    return [self[alias] for alias in self]
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/utils.py", line 81, in __getitem__
    engine = engine_cls(params)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 25, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 43, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 108, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 121, in get_package_libraries
    module = import_module(entry[1])
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/website/mysite/blog/templatetags/blog_tags.py", line 19, in <module>
    @register.assignment_tag
AttributeError: 'Library' object has no attribute 'assignment_tag'
[08/Nov/2018 05:52:26] "GET /index/ HTTP/1.0" 500 149455
[08/Nov/2018 05:52:26] "GET /index HTTP/1.0" 301 0
Not Found: /favicon.ico
[08/Nov/2018 05:52:27] "GET /favicon.ico HTTP/1.0" 404 2476
Not Found: /
[08/Nov/2018 06:06:05] "GET / HTTP/1.0" 404 2425
Not Found: /
[08/Nov/2018 06:18:05] "GET / HTTP/1.0" 404 2425
Not Found: /index.html
[08/Nov/2018 06:57:01] "GET /index.html HTTP/1.0" 404 2473
Not Found: /robots.txt
[08/Nov/2018 07:28:54] "GET /robots.txt HTTP/1.0" 404 2473
Not Found: /favicon.ico
[08/Nov/2018 07:28:54] "GET /favicon.ico HTTP/1.0" 404 2476
Internal Server Error: /index/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/utils.py", line 66, in __getitem__
    return self._engines[alias]
KeyError: 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/website/mysite/blog/views.py", line 53, in home
    'posts':posts})
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/loader.py", line 12, in get_template
    engines = _engine_list(using)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/loader.py", line 66, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/utils.py", line 90, in all
    return [self[alias] for alias in self]
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/utils.py", line 90, in <listcomp>
    return [self[alias] for alias in self]
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/utils.py", line 81, in __getitem__
    engine = engine_cls(params)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 25, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 43, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 108, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 121, in get_package_libraries
    module = import_module(entry[1])
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/website/mysite/blog/templatetags/blog_tags.py", line 19, in <module>
    @register.assignment_tag
AttributeError: 'Library' object has no attribute 'assignment_tag'
[08/Nov/2018 07:36:02] "GET /index/ HTTP/1.0" 500 148734
Not Found: /favicon.ico
[08/Nov/2018 07:55:32] "GET /favicon.ico HTTP/1.0" 404 2476
Not Found: /
[08/Nov/2018 08:13:35] "GET / HTTP/1.0" 404 2425
Not Found: /
[08/Nov/2018 08:27:20] "GET / HTTP/1.0" 404 2425
Not Found: /
[08/Nov/2018 08:34:08] "GET / HTTP/1.0" 404 2425
Not Found: /favicon.ico
[08/Nov/2018 08:46:12] "GET /favicon.ico HTTP/1.0" 404 2476
Not Found: /
[08/Nov/2018 08:46:55] "GET / HTTP/1.0" 404 2425
Not Found: /
[08/Nov/2018 09:10:47] "GET / HTTP/1.0" 404 2425
Not Found: /
[08/Nov/2018 09:20:15] "GET / HTTP/1.0" 404 2425
Not Found: /
[08/Nov/2018 09:29:25] "GET / HTTP/1.0" 404 2425
Not Found: /robots.txt
[08/Nov/2018 09:42:31] "GET /robots.txt HTTP/1.0" 404 2473
Not Found: /index.html
[08/Nov/2018 09:42:31] "GET /index.html HTTP/1.0" 404 2473
Not Found: /
[08/Nov/2018 09:55:19] "GET / HTTP/1.0" 404 2425
Not Found: /w00tw00t.at.blackhats.romanian.anti-sec:)
[08/Nov/2018 10:04:52] "GET /w00tw00t.at.blackhats.romanian.anti-sec:) HTTP/1.0" 404 2566
Not Found: /phpMyAdmin/scripts/setup.php
[08/Nov/2018 10:04:53] "GET /phpMyAdmin/scripts/setup.php HTTP/1.0" 404 2527
Not Found: /phpmyadmin/scripts/setup.php
[08/Nov/2018 10:04:53] "GET /phpmyadmin/scripts/setup.php HTTP/1.0" 404 2527
Not Found: /pma/scripts/setup.php
[08/Nov/2018 10:04:53] "GET /pma/scripts/setup.php HTTP/1.0" 404 2506
Not Found: /myadmin/scripts/setup.php
[08/Nov/2018 10:04:53] "GET /myadmin/scripts/setup.php HTTP/1.0" 404 2518
Not Found: /MyAdmin/scripts/setup.php
[08/Nov/2018 10:04:53] "GET /MyAdmin/scripts/setup.php HTTP/1.0" 404 2518
Not Found: /
[08/Nov/2018 10:33:19] "GET / HTTP/1.0" 404 2425
Not Found: /JS/jquery-animate-css-rotate-scale.js
[08/Nov/2018 10:53:48] "GET /JS/jquery-animate-css-rotate-scale.js HTTP/1.0" 404 2554
Not Found: /JS/jquery.scrollTo.min.js
[08/Nov/2018 10:53:49] "GET /JS/jquery.scrollTo.min.js HTTP/1.0" 404 2518
Not Found: /CSS/spore-font.css
[08/Nov/2018 10:53:50] "GET /CSS/spore-font.css HTTP/1.0" 404 2497
Not Found: /JS/fastclick.js
[08/Nov/2018 10:53:50] "GET /JS/fastclick.js HTTP/1.0" 404 2488
Not Found: /JS/wow.min.js
[08/Nov/2018 10:53:51] "GET /JS/wow.min.js HTTP/1.0" 404 2482
Not Found: /CSS/animate.css
[08/Nov/2018 10:53:51] "GET /CSS/animate.css HTTP/1.0" 404 2488
Not Found: /IMG/trame.svg
[08/Nov/2018 10:54:00] "GET /IMG/trame.svg HTTP/1.0" 404 2482
Not Found: /IMG/logotop.svg
[08/Nov/2018 10:54:00] "GET /IMG/logotop.svg HTTP/1.0" 404 2488
Not Found: /IMG/plus.svg
[08/Nov/2018 10:54:01] "GET /IMG/plus.svg HTTP/1.0" 404 2479
Not Found: /IMG/cross.svg
[08/Nov/2018 10:54:01] "GET /IMG/cross.svg HTTP/1.0" 404 2482
Not Found: /spore/spore-post2.html
[08/Nov/2018 10:55:49] "GET /spore/spore-post2.html HTTP/1.0" 404 2509
Not Found: /
[08/Nov/2018 11:12:54] "GET / HTTP/1.0" 404 2425
Not Found: /
[08/Nov/2018 11:33:32] "GET / HTTP/1.0" 404 2425
Not Found: /style.css
[08/Nov/2018 11:33:35] "GET /style.css HTTP/1.0" 404 2470
Not Found: /favicon.ico
[08/Nov/2018 11:33:37] "GET /favicon.ico HTTP/1.0" 404 2476
Not Found: /
[08/Nov/2018 11:42:58] "GET / HTTP/1.0" 404 2425
Not Found: /
[08/Nov/2018 12:07:58] "GET / HTTP/1.0" 404 2425
Not Found: /
[08/Nov/2018 13:13:24] "GET / HTTP/1.0" 404 2425
Not Found: /
[08/Nov/2018 13:29:40] "GET / HTTP/1.0" 404 2425
Not Found: /
[08/Nov/2018 13:53:05] "GET / HTTP/1.0" 404 2425
Not Found: /
[08/Nov/2018 13:57:52] "GET / HTTP/1.0" 404 2425
Not Found: /
[08/Nov/2018 14:02:18] "GET / HTTP/1.0" 404 2425
Not Found: /
[08/Nov/2018 14:02:18] "GET / HTTP/1.0" 404 2425
Not Found: /
[08/Nov/2018 14:02:48] "GET / HTTP/1.0" 404 2425
Not Found: /
[08/Nov/2018 14:02:49] "GET / HTTP/1.0" 404 2425
Not Found: /
[08/Nov/2018 14:10:51] "GET / HTTP/1.0" 404 2425
Not Found: /
[08/Nov/2018 14:15:41] "GET / HTTP/1.0" 404 2425
Not Found: /
[08/Nov/2018 14:16:29] "GET / HTTP/1.0" 404 2425
Not Found: /
[08/Nov/2018 14:17:15] "GET / HTTP/1.0" 404 2425
Not Found: /pma/scripts/setup.php
[08/Nov/2018 14:19:12] "GET /pma/scripts/setup.php HTTP/1.0" 404 2506
Internal Server Error: /index/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/utils.py", line 66, in __getitem__
    return self._engines[alias]
KeyError: 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/website/mysite/blog/views.py", line 53, in home
    'posts':posts})
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/loader.py", line 12, in get_template
    engines = _engine_list(using)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/loader.py", line 66, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/utils.py", line 90, in all
    return [self[alias] for alias in self]
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/utils.py", line 90, in <listcomp>
    return [self[alias] for alias in self]
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/utils.py", line 81, in __getitem__
    engine = engine_cls(params)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 25, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 43, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 108, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 121, in get_package_libraries
    module = import_module(entry[1])
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/website/mysite/blog/templatetags/blog_tags.py", line 19, in <module>
    @register.assignment_tag
AttributeError: 'Library' object has no attribute 'assignment_tag'
[08/Nov/2018 14:23:21] "GET /index/ HTTP/1.0" 500 149329
Not Found: /favicon.ico
[08/Nov/2018 14:23:22] "GET /favicon.ico HTTP/1.0" 404 2476
Not Found: /
[08/Nov/2018 14:53:59] "GET / HTTP/1.0" 404 2425
Not Found: /
[08/Nov/2018 14:55:53] "GET / HTTP/1.0" 404 2425
